Implement leap motion hand tracking (#5)
* Import codebase

* Remove SDK components falsly checked in

* Update ultraleap module to master branch

* Update UnityModules to main branch

* Refactor data provider to fit new hands flow

* Allow unsafe code for Ultraleap assembly

error CS0227: Unsafe code may only appear if compiling with /unsafe. Enable "Allow 'unsafe' code" in the inspector for 'Packages/com.xrtk.ultraleap/Runtime/XRTK.Ultraleap.asmdef' to fix this error.

* Temp remove WSAPlayer config for plugin

WMR\XRTK-Core\Plugins\ARM64\LeapC.dll" because it was not found.

* Wrap up LeapMotionHandControllerDataProvider

* Clean up meshing related code

* Fix right to left-hand-system conversion

* Fix palm position

* Fix palm rotation

* Restore assembly reference to LeapCSharp and update submodule checkout

* Formatting

* Rename operation modes

* Create platform configurations profile

* Temp implementation to check for leap service

* Use Ultraleap instead of leap motion where possible

* Move coordinate conversion to extension

* Fix left handed conversion for rotations

* Fill missing joints

* Clean up converter

* Fix offset docs

* Fix hand root pose offset

* Minor reformat for GetHandOffsetPose

* Fix inspector still referencing old serialized prop name

* Adjust desktop mode offset for comfort

* Move conversion into data provider

* Fix inspector help text

* Improve ultraleap docs

* Fix rotation conversion

* Fix desktop offset does not take camera rotation into account

* Fold in playspace rotation

* Fix missing space in inspector

* Create standalone hand profiles

* Introduce UltraleapDeviceOffsetMode config

* Request HML optimize policy if in headset mounted mode

* Add device offset properties to data provider

* Add missing docs

* Improve formatting in data provider

* Use proprties for offset pose

* Implement Ultraleap package installer

* Update to 2014.4 LTS

* Introduce UltraleapFrameOptimizationMode

* Introduce ReconnectionInterval and MaxReconnectionAttempts

* Implement UltraleapFrameOptimizationMode

* Improved and streamlined hand lifecycle

* Remove unused CurrentFrame, CurrentFixedFrame properties

* Fix root transform (need to fold in playspace now)

* Fix teleportation

* Compute pointer pose (best I can do for now)

* updated breaking changes from core

* removed missing asmdef reference

* Created new XRTK.Ultraleap.Editor.Inspectors.asmdef

fixed reference to copied LeapMotion.LeapCSharp.asmdef (meta wasn't copied)

* fixed wsa x64 parsing

* check if UltraleapPluginUtility is running correctly

* debug more things

* fix inspector platform

* removed debug logs

* updated license

* updated leap motion submodule checkout

updated build pipeline

* added simple test script

* updated project to 2019.4.28

updated core dependencies

* added assembly info

bumped verson to 0.3.0

* Removed platform and set the package installer to windows universal and standalone only

* fixed slashes

* updated build targets

* updated ultrealeap submodule

* only build for standalone windows

* updated applicatoin identifier

* replaced plugin utility with submodule reference

* Revert "replaced plugin utility with submodule reference"

This reverts commit e4e339a40fb4867beb2713c3315d7ba6bb1bca85.

* added missing assembly infos

* only create controller in play mode

Co-authored-by: Stephen Hodgson <hodgson.designs@gmail.com>